---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-variables/ and in linters documentation

# Flavor: python (optimized for Python projects)
FLAVOR_SUGGESTIONS: false

# Activate specific linters
APPLY_FIXES: none # Set to 'all' to apply fixes automatically
DEFAULT_BRANCH: main
DEFAULT_WORKSPACE: /tmp/lint

# File/directory patterns to exclude
EXCLUDED_DIRECTORIES:
  - .git
  - .github
  - .mypy_cache
  - .pytest_cache
  - .ruff_cache
  - __pycache__
  - .venv
  - venv
  - node_modules
  - dist
  - build
  - htmlcov
  - megalinter-reports
  - .terraform
  - terraform/.terraform

# Linters to enable/disable
ENABLE:
  - PYTHON
  - TERRAFORM
  - YAML
  - JSON
  - MARKDOWN
  - BASH
  - SPELL
  - REPOSITORY

DISABLE:
  - COPYPASTE # Can be noisy for similar function patterns
  - CSS
  - HTML
  - JAVASCRIPT
  - TYPESCRIPT
  - SQL

# Python linters configuration
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_ARGUMENTS: --config pyproject.toml
PYTHON_MYPY_CONFIG_FILE: pyproject.toml
PYTHON_MYPY_ARGUMENTS: --config-file pyproject.toml
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_CONFIG_FILE: pyproject.toml
PYTHON_PYLINT_CONFIG_FILE: pyproject.toml
PYTHON_BANDIT_CONFIG_FILE: pyproject.toml
PYTHON_BANDIT_ARGUMENTS: -c pyproject.toml

# Use Ruff instead of other Python linters (it's faster and modern)
PYTHON_BLACK_DISABLE_ERRORS: true
PYTHON_ISORT_DISABLE_ERRORS: true
PYTHON_PYLINT_DISABLE_ERRORS: true
PYTHON_FLAKE8_DISABLE_ERRORS: true

# Terraform configuration
TERRAFORM_TERRAFORM_FMT_ARGUMENTS: -recursive
TERRAFORM_TFLINT_CONFIG_FILE: .tflint.hcl
TERRAFORM_TFLINT_ARGUMENTS: --config .tflint.hcl
TERRAFORM_CHECKOV_ARGUMENTS: --framework terraform --quiet

# Markdown configuration
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: true # Don't fail on markdown issues

# YAML configuration
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml
YAML_PRETTIER_DISABLE_ERRORS: true

# Spell checker configuration
SPELL_CSPELL_DISABLE_ERRORS: true # Don't fail on spell check issues
SPELL_MISSPELL_DISABLE_ERRORS: true

# Repository linters
REPOSITORY_CHECKOV_DISABLE_ERRORS: true
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true
REPOSITORY_DUSTILOCK_DISABLE_ERRORS: true
REPOSITORY_GIT_DIFF_DISABLE_ERRORS: true
REPOSITORY_SECRETLINT_DISABLE_ERRORS: true
REPOSITORY_TRIVY_DISABLE_ERRORS: true

# Reporting
FILEIO_REPORTER: false
UPDATED_SOURCES_REPORTER: true
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
EMAIL_REPORTER: false

# Performance
PARALLEL: true
LOG_LEVEL: INFO
SHOW_ELAPSED_TIME: true

# File types to lint
FILTER_REGEX_INCLUDE: (\.py$|\.tf$|\.hcl$|\.yml$|\.yaml$|\.json$|\.md$|\.sh$)
FILTER_REGEX_EXCLUDE: (\.min\.js$|\.min\.css$|package-lock\.json|poetry\.lock|Pipfile\.lock)

# Pre/Post commands
# PRE_COMMANDS:
#   - command: echo "Starting MegaLinter"
#     cwd: workspace

# POST_COMMANDS:
#   - command: echo "MegaLinter completed"
#     cwd: workspace

# Format output
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
PRINT_ALL_FILES: false

# GitHub specific
GITHUB_WORKSPACE: /tmp/lint

# Validate all codebase
VALIDATE_ALL_CODEBASE: true

# Clear reports before running
CLEAR_REPORT_FOLDER: true

# Console reporter
CONSOLE_REPORTER: true

# Text reporter
TEXT_REPORTER: true
TEXT_REPORTER_SUB_FOLDER: linters_logs

# TAP reporter
TAP_REPORTER: true
TAP_REPORTER_SUB_FOLDER: tap

# JSON reporter
JSON_REPORTER: true

# SARIF reporter (for GitHub Security)
SARIF_REPORTER: true

# Disable specific Python linters that overlap with Ruff
PYTHON_BLACK_FILTER_REGEX_EXCLUDE: .*
PYTHON_ISORT_FILTER_REGEX_EXCLUDE: .*
PYTHON_PYLINT_FILTER_REGEX_EXCLUDE: .*
PYTHON_FLAKE8_FILTER_REGEX_EXCLUDE: .*
PYTHON_PYRIGHT_FILTER_REGEX_EXCLUDE: .*
