---
# yamllint configuration for the project
extends: default

rules:
  # Line length - relaxed for readability
  line-length:
    max: 120
    level: warning

  # Indentation - 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    min-spaces-from-content: 1
    require-starting-space: true
    ignore-shebangs: true

  # Document directives
  document-start:
    present: true

  # Trailing spaces
  trailing-spaces: enable

  # Empty lines
  empty-lines:
    max: 2

  # Key duplicates
  key-duplicates: enable

  # Truthy values (allow yes/no, true/false, on/off)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Quoted strings - allow both single and double quotes
  quoted-strings:
    quote-type: any
    required: only-when-needed

# Ignore specific files/patterns
ignore: |
  .github/
  node_modules/
  .venv/
  venv/
  dist/
  build/
  *.min.yaml
  *.min.yml
  .terraform/
